In [2]:
import sqlite3
import pandas as pd

df = pd.read_csv('../data/processed/creditcard_with_features.csv')
conn = sqlite3.connect('../data/fraud.db')
df.to_sql(
    'transactions',
    conn,
    if_exists='replace',
    index=False
)

print("✅ Loaded into SQLite — table: transactions")

✅ Loaded into SQLite — table: transactions

In [4]:
with open('../sql/fraud_analysis_queries.sql', 'r') as file:
    sql_content = file.read()

In [5]:
queries = sql_content.split(';')

In [6]:
query1 = queries[0]

df1 = pd.read_sql_query(query1, conn)
df1

,Total_Transactions,Total_Fraud,Fraud_Rate_Pct,Avg_Fraud_Amount,Avg_Legit_Amount,Total_Fraud_Amount
0,284807,492,0.1727,122.21,88.29,60127.97

In [7]:
df1.to_csv('../data/sql_outputs/q1_overall_fraud_summary.csv', index=False)

In [8]:
query2 = queries[1]

df2 = pd.read_sql_query(query2, conn)
df2

  Amount_bucket  Total_Txns  Fraud_Count  Fraud_Rate_Pct
0          None        1825           27           1.479
1      500-1000        6202           26           0.419
2         1000+        2940            9           0.306
3       100-500       47366           95           0.201
4        50-100       37254           56           0.150
5          0-50      189220          279           0.147

In [9]:
df1.to_csv('../data/sql_outputs/q2_fraud_rate_by_amount_bucket.csv', index=False)

In [10]:
query3 = queries[2]

df3 = pd.read_sql_query(query3, conn)
df3

   TimeOfDay  Transactions  Fraud_Count  Fraud_Rate_Pct
0      Night         23935          124           0.518
1    Morning         70917          118           0.166
2  Afternoon         96433          134           0.139
3    Evening         93522          116           0.124

In [11]:
df1.to_csv('../data/sql_outputs/q3_fraud_by_timeofday.csv', index=False)

In [12]:
query4 = queries[3]

df4 = pd.read_sql_query(query4, conn)
df4

    Hour_of_Day  Transactions  Fraud  Fraud_Rate_Pct
0             0          7695      6          0.0780
1             1          4220     10          0.2370
2             2          3328     57          1.7127
3             3          3492     17          0.4868
4             4          2209     23          1.0412
5             5          2990     11          0.3679
6             6          4101      9          0.2195
7             7          7243     23          0.3175
8             8         10276      9          0.0876
9             9         15838     16          0.1010
10           10         16598      8          0.0482
11           11         16856     53          0.3144
12           12         15420     17          0.1102
13           13         15365     17          0.1106
14           14         16570     23          0.1388
15           15         16461     26          0.1579
16           16         16453     22          0.1337
17           17         16166     29          0.1794
18           18         17039     33          0.1937
19           19         15649     19          0.1214
20           20         16756     18          0.1074
21           21         17703     16          0.0904
22           22         15441      9          0.0583
23           23         10938     21          0.1920

In [13]:
df1.to_csv('../data/sql_outputs/q4_fraud_rate_by_hour.csv', index=False)

In [14]:
query5 = queries[4]

df5 = pd.read_sql_query(query5, conn)
df5

,Amount,Hour,TimeOfDay,Amount_bucket,V1,V2,V3,V4
0,2125.87,10.1,Morning,1000+,-2.003460,-7.159042,-4.050976,1.309580
1,1809.68,2.5,Night,1000+,-3.499108,0.258555,-4.489558,4.853894
2,1504.93,18.9,Evening,1000+,-1.600211,-3.488130,-6.459303,3.246816
3,1402.16,17.4,Afternoon,1000+,-5.344665,-0.285760,-3.835616,5.337048
4,1389.56,16.4,Afternoon,1000+,-2.326922,-3.348439,-3.513408,3.175060
5,1354.25,18.2,Evening,1000+,-2.923827,1.524837,-3.018758,3.289291
6,1335.00,13.0,Afternoon,1000+,-1.212682,-2.484824,-6.397186,3.670562
7,1218.89,5.0,Night,1000+,-12.224021,3.854150,-12.466766,9.648311
8,1096.99,18.9,Evening,1000+,-0.082983,-3.935919,-2.616709,0.163310
9,996.27,17.0,Afternoon,500-1000,-1.611877,-0.408410,-3.829762,6.249462
10,925.31,13.4,Afternoon,500-1000,-0.967767,2.098019,-5.222929,6.514573
11,829.41,0.4,Night,500-1000,-1.360293,-0.458069,-0.700404,2.737229
12,824.83,19.6,Evening,500-1000,-2.271755,-0.457655,-2.589055,2.230778
13,802.52,11.6,Morning,500-1000,-2.144411,1.073499,-2.773663,1.384394
14,776.83,11.0,Morning,500-1000,-0.964567,-1.643541,-0.187727,1.158253
15,766.36,5.0,Night,500-1000,-5.187878,6.967709,-13.510931,8.617895
16,730.86,7.8,Morning,500-1000,-2.787248,-0.071340,-1.505288,3.361777
17,727.91,14.6,Afternoon,500-1000,-2.356348,1.746360,-6.374624,1.772205
18,723.21,12.4,Afternoon,500-1000,0.469750,-1.237555,-1.767341,4.833490
19,723.21,14.9,Afternoon,500-1000,-2.921944,-0.228062,-5.877289,2.201884

In [15]:
df1.to_csv('../data/sql_outputs/q5_top20_high_value_fraud.csv', index=False)

In [16]:
query6 = queries[5]

df6 = pd.read_sql_query(query6, conn)
df6

    Hour_of_Day  Total_Transactions  Fraud_Count  Total_Volume
0             0                7695            6     464208.26
1             1                4220           10     264325.45
2             2                3328           57     233820.68
3             3                3492           17     181852.16
4             4                2209           23     170179.23
5             5                2990           11     151520.18
6             6                4101            9     266812.20
7             7                7243           23     491209.10
8             8               10276            9     912213.29
9             9               15838           16    1628829.82
10           10               16598            8    1820354.38
11           11               16856           53    1847641.57
12           12               15420           17    1635221.81
13           13               15365           17    1520510.55
14           14               16570           23    1715632.94
15           15               16461           26    1679009.61
16           16               16453           22    1702609.91
17           17               16166           29    1589499.95
18           18               17039           33    1316311.34
19           19               15649           19    1220410.35
20           20               16756           18    1249073.10
21           21               17703           16    1268615.18
22           22               15441            9    1078955.79
23           23               10938           21     753773.16

In [17]:
df1.to_csv('../data/sql_outputs/q6_transaction_volume_trend.csv', index=False)

In [18]:
query7 = queries[6]

df7 = pd.read_sql_query(query7, conn)
df7

     Amount_Type   Count  Fraud_Count  Fraud_Rate
0    Micro (<$2)   46990          195        0.41
1         Normal  187493          243        0.13
2  Small ($2-10)   50324           54        0.11

In [19]:
df1.to_csv('../data/sql_outputs/q7_velocity_detection.csv', index=False)

In [20]:
query8 = queries[7]

df8 = pd.read_sql_query(query8, conn)
df8

              Time_Window  Transactions  Fraud  Fraud_Rate_Pct
0  Late Night Risk Window         31882    134           0.420
1            Normal Hours        252925    358           0.142

In [21]:
df1.to_csv('../data/sql_outputs/q8_night_fraud_concentration.csv', index=False)

In [22]:
query9 = queries[8]

df9 = pd.read_sql_query(query9, conn)
df9

   Hour_of_Day  Fraud_Amount_Lost
0           11            6570.73
1           18            6345.14
2            2            4517.98
3           16            4505.45
4           14            3641.12
5           12            3406.54
6           17            3373.50
7           23            3143.12
8            7            2757.78
9           10            2349.61

In [23]:
df1.to_csv('../data/sql_outputs/q9_financial_exposure_by_hour.csv', index=False)

In [24]:
query10 = queries[9]

df10 = pd.read_sql_query(query10, conn)
df10

  Amount_bucket  Transactions  Fraud  Cumulative_Fraud
0          0-50        189220    279               279
1       100-500         47366     95               374
2        50-100         37254     56               430
3          None          1825     27               457
4      500-1000          6202     26               483
5         1000+          2940      9               492

In [25]:
df1.to_csv('../data/sql_outputs/q10_cumulative_fraud_detection.csv', index=False)